### PR TITLE
Minor code reduction

### PR DESCRIPTION
**Pull request by cclauss**

### CODE REVIEW

**Comment by dpriskorn** [comment]
The linter seems to always fail. I tried reproducing, but I'm on W10 and  did not succeed in git bash

**Comment by cclauss** [comment]
I needed to add the missing return statements and `"pyupgrade --keep-runtime-typing --py37-plus src/__init__.py`

**Comment by dpriskorn** [comment]
Thank you for the PR. isodate() should return a datetime object, not str. I'm not sure how to do that in a more concise way. Any ideas?

**Comment by dpriskorn** [comment]
I merged main into this and now it LGTM. Thanks!

**Pull request merged**
