### PR TITLE
GitHub Action: Run pytests that do not require userid and password

### PR DESCRIPTION
**Pull request by cclauss**
Trying to get pytest to pass on GitHub Actions...
* `pytest --ignore` test_wcdimportbot.py and test_wikicitations.py because some tests require a valid userid and password.

@dpriskorn Can you please help me understand why two pytests that are failing on `__find_number__(string='isbn_13')`

Should `__find_number__()` be changed or should the pytests be changed?

### CODE REVIEW

**Comment by cclauss** [comment]
I tried to special case but the pytests still fail.
```
    def __find_number__(string: str) -> Optional[int]:
        """Find all numbers in a string"""
        if string.startswith(("first1", "isbn_1", "last1")):
            return None
```

**Comment by dpriskorn** [comment]
I rewrote find_numbers, see #24

**Comment by dpriskorn** [comment]
Yes, a good amount of the tests need to write and delete from a Wikibase. Unfortunately, we don't currently have access to a test Wikibase installation. Once the new Wikibase SAAS is up in a few months, I hope to have one to run tests against.

**Comment by cclauss** [comment]
Regex loves raw strings: Fix invalid escape sequence '\d' by using r'\d' instead.

[Xfail](https://docs.pytest.org/en/7.1.x/how-to/skipping.html#xfail-mark-test-functions-as-expected-to-fail) the test [test_get_wcdqid_from_hash_via_sparql](https://github.com/internetarchive/wcdimportbot/pull/22/commits/70e17b6199a8100b0062352feeadc6ffd54ab846) only when [tests are being run on continuous integration](https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables) because our GitHub Actions do not yet have access to login credentials.

**Comment by cclauss** [comment]
$ `pytest --durations=10 --ignore=tests/test_wcdimportbot.py .`
```
============================= test session starts ==============================
platform linux -- Python 3.10.4, pytest-7.1.2, pluggy-1.0.0
rootdir: /home/runner/work/wcdimportbot/wcdimportbot
collected 29 items

tests/test_cache.py ..                                                   [  6%]
tests/test_english_wikipedia_page_reference.py ........                  [ 34%]
tests/test_person.py ...                                                 [ 44%]
tests/test_ssdb_database.py ..                                           [ 51%]
tests/test_wikicitations.py ..ss.xxx.xx                                  [ 89%]
tests/test_wikipedia_page.py ..x                                         [100%]

============================= slowest 10 durations =============================
31.54s call     tests/test_wikicitations.py::TestWikiCitations::test_get_items_via_sparql
8.88s call     tests/test_wikipedia_page.py::TestWikipediaPage::test_get_wcdqid_from_hash_via_sparql
7.94s call     tests/test_wikicitations.py::TestWikiCitations::test_uploading_a_page_reference_and_website_item
1.67s call     tests/test_wikicitations.py::TestWikiCitations::test_prepare_and_upload_website_item
1.40s call     tests/test_wikipedia_page.py::TestWikipediaPage::test_fix_dash
0.95s call     tests/test_wikicitations.py::TestWikiCitations::test_prepare_and_upload_wikipedia_page_item_valid_qid
0.79s call     tests/test_wikicitations.py::TestWikiCitations::test_prepare_new_reference_item
0.54s call     tests/test_wikicitations.py::TestWikiCitations::test_prepare_new_wikipedia_page_item_valid_qid
0.22s call     tests/test_wikicitations.py::TestWikiCitations::test_prepare_new_wikipedia_page_item_invalid_qid
0.13s call     tests/test_wikipedia_page.py::TestWikipediaPage::test_fetch_page_data_and_parse_the_wikitext
================== 21 passed, 2 skipped, 6 xfailed in 55.15s ===================
```

**Comment by dpriskorn** [comment]
LGTM. Thanks for the work on this!

**Pull request merged**
